/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author jose lopez
 */
public class codigo_planillab extends javax.swing.JFrame {

    public codigo_planillab() {
        initComponents();
         this.setTitle("CODIGO PLANILLA CON BASE DE DATOS");
        this.setLocationRelativeTo(codigo_planillab.this);
        this.setResizable(false);
        File archivo= new File("C:\\Users\\jose lopez\\Documents\\programas\\codigos\\planilla con base de datos\\planilla.java");
          try {
           BufferedReader leer = new BufferedReader(new FileReader(archivo));
           String linea = leer.readLine();
           while(linea != null){
               jTextArea1.append(linea+"\n");
              linea = leer.readLine();
           }
          } catch (Exception ex) {
          System.err.println("no se abrio bien el archivo"+ex.toString());
        
        }
           File archivo1= new File("C:\\Users\\jose lopez\\Documents\\programas\\codigos\\planilla con base de datos\\eliminacion_de_datos.java");
          try {
           BufferedReader leer = new BufferedReader(new FileReader(archivo1));
           String linea = leer.readLine();
           while(linea != null){
               jTextArea2.append(linea+"\n");
              linea = leer.readLine();
           }
          } catch (Exception ex) {
          System.err.println("no se abrio bien el archivo"+ex.toString());
        
        }
           File archivo2= new File("C:\\Users\\jose lopez\\Documents\\programas\\codigos\\planilla con base de datos\\ingreso_concepto.java");
          try {
           BufferedReader leer = new BufferedReader(new FileReader(archivo2));
           String linea = leer.readLine();
           while(linea != null){
               jTextArea3.append(linea+"\n");
              linea = leer.readLine();
           }
          } catch (Exception ex) {
          System.err.println("no se abrio bien el archivo"+ex.toString());
        
        }
             File archivo3= new File("C:\\Users\\jose lopez\\Documents\\programas\\codigos\\planilla con base de datos\\ingreso_empleado.java");
          try {
           BufferedReader leer = new BufferedReader(new FileReader(archivo3));
           String linea = leer.readLine();
           while(linea != null){
               jTextArea4.append(linea+"\n");
              linea = leer.readLine();
           }
          } catch (Exception ex) {
          System.err.println("no se abrio bien el archivo"+ex.toString());
        
        }
             File archivo4= new File("C:\\Users\\jose lopez\\Documents\\programas\\codigos\\planilla con base de datos\\ingreso_usuario.java");
          try {
           BufferedReader leer = new BufferedReader(new FileReader(archivo4));
           String linea = leer.readLine();
           while(linea != null){
               jTextArea5.append(linea+"\n");
              linea = leer.readLine();
           }
          } catch (Exception ex) {
          System.err.println("no se abrio bien el archivo"+ex.toString());
        
        }
             File archivo5= new File("C:\\Users\\jose lopez\\Documents\\programas\\codigos\\planilla con base de datos\\nomina_detalle.java");
          try {
           BufferedReader leer = new BufferedReader(new FileReader(archivo5));
           String linea = leer.readLine();
           while(linea != null){
               jTextArea6.append(linea+"\n");
              linea = leer.readLine();
           }
          } catch (Exception ex) {
          System.err.println("no se abrio bien el archivo"+ex.toString());
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 23, 444, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 73, 444, 420));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 73, 501, 420));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 444, 390));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 501, 390));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 73, 499, 420));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 520, 499, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        planillab b = new planillab();
        b.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(codigo_planillab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(codigo_planillab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(codigo_planillab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(codigo_planillab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new codigo_planillab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}
