/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author jose lopez
 */
public class codigo_torres extends javax.swing.JFrame {

    /**
     * Creates new form codigo_torres
     */
    public codigo_torres() {
        initComponents();
         this.setTitle("CODIGO LISTAS");
        this.setLocationRelativeTo(codigo_torres.this);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 25, 460, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("/*\nNOMBRE: JOSE ESTANISLAO LOPEZ TUBAC\n0901-17-12\n*/\npackage torres;\n\nimport java.util.Scanner;\nimport javax.swing.JOptionPane;\n\npublic class Torres {\n    public static void main(String[] args) {\n       Scanner leer = new Scanner (System.in);\n       String discos;\n       int cantidad;\n       discos = JOptionPane.showInputDialog(null, \"INGRESE LA CANTIDAD DE DISCOS QUE DESEA\");\n       cantidad = Integer.parseInt(discos);\n        int movimientos = (int)(Math.pow(2, cantidad) -1);\n        System.out.println(\"LA CANTIDAD DE DISCOS ES \"+cantidad);\n        System.out.println(\"EL NUMERO MINIMO DE MOVIMIENTOS ES \"+movimientos);\n        for(int i = 1; i <= cantidad; i++)\n        {\n           System.out.print(\"[\"+i+\"]\\n\"); \n        }\n        System.out.print(\"TORRE 1 \\tTORRE 2 \\tTORRE 3\\n\");\n       jannoi(cantidad,1,2,3);\n    }\n \n    public static void jannoi(int cantidad, int inicio,int auxiliar, int destino) {\n    \n        if(cantidad == 1)\n       {\n          System.out.println(\"DISCO: [\"+cantidad+\"] DE LA TORRE \"+inicio+\" A LA TORRE \"+destino);   \n       }\n       else\n            {\n                jannoi(cantidad - 1,inicio, destino, auxiliar);\n                \n                System.out.println(\"DISCO: [\"+cantidad+\"] DE LA TORRE \"+inicio+\" A LA TORRE \"+destino);\n                \n                jannoi(cantidad - 1,auxiliar, inicio, destino);\n            }\n        }\n  \n    }\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 92, 468, 328));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("package torres_de_hanoi;\n\npublic class pila {\n    private int contador = 0;\n    private Nodo cabeza;\n\n    public int getContador() {\n        return contador;\n    }\n\n    public Nodo getCabeza() {\n        return cabeza;\n    }\n    public void push(Nodo  N)\n    {\n        contador++;\n        if(cabeza ==  null)\n        {\n        cabeza = N;\n        }else\n        {\n        N.setAbajo(cabeza);\n        cabeza.setArriba(N);\n        cabeza = N;\n        }\n    }\n    public void pop()\n    {\n    if(contador > 0)\n    {\n        contador--;\n        cabeza = cabeza.getAbajo();\n    }\n    }\n    public String peek()\n    {\n        return cabeza.getDato();\n    }\n    \n}\n");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 510, 328));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("package torres_de_hanoi;\n\npublic class Nodo {\n  private String dato;\n  private Nodo arriba;\n  private Nodo abajo;\n\n    public String getDato() {\n        return dato;\n    }\n\n    public void setDato(String dato) {\n        this.dato = dato;\n    }\n\n    public Nodo getArriba() {\n        return arriba;\n    }\n\n    public void setArriba(Nodo arriba) {\n        this.arriba = arriba;\n    }\n\n    public Nodo getAbajo() {\n        return abajo;\n    }\n\n    public void setAbajo(Nodo abajo) {\n        this.abajo = abajo;\n    }\n  \n  \n  \n}\n");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 446, 468, 325));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        torres l = new torres();
        l.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(codigo_torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(codigo_torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(codigo_torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(codigo_torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new codigo_torres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
