/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programas;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author jose lopez
 */
public class planilla extends javax.swing.JFrame {

    /**
     * Creates new form planilla
     */
    public planilla() {
        initComponents();
        this.setTitle("PLANILLA SIN BASE DE DATOS");
        this.setLocationRelativeTo(planilla.this);
        this.setResizable(false);
        this.setSize(500,660);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvideo = new javax.swing.JButton();
        btnrepositorio = new javax.swing.JButton();
        btncodigo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programas/youtube.png"))); // NOI18N
        btnvideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvideoActionPerformed(evt);
            }
        });
        getContentPane().add(btnvideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, 110));

        btnrepositorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programas/logo-de-github.png"))); // NOI18N
        btnrepositorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrepositorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnrepositorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 170, 140));

        btncodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programas/dato.png"))); // NOI18N
        btncodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncodigoActionPerformed(evt);
            }
        });
        getContentPane().add(btncodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 160, 140));

        jLabel1.setText("LINK DE VIDEO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel2.setText("LINK DE REPOSITORIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jLabel3.setText("CODIGO EN JAVA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        jLabel4.setText("PROGRAMA DE PLANILLA SIN BASE DE DATOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 150, -1));

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvideoActionPerformed
       
        try{
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=V6Yuvn8JYMk"));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"NO SE PUDO CONECTAR CON LA PAGINA WEB"+e);
        }
        
    }//GEN-LAST:event_btnvideoActionPerformed

    private void btnrepositorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrepositorioActionPerformed
          
        try{
            Desktop.getDesktop().browse(new URI("https://github.com/chipa3/programacion3/tree/master/planilla%20sin%20base%20de%20datos"));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"NO SE PUDO CONECTAR CON LA PAGINA WEB"+e);
        }
    }//GEN-LAST:event_btnrepositorioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu m = new menu();
        m.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void abrirarchivo(String archivo){

} 
    private void btncodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncodigoActionPerformed
        codigo_planilla c = new codigo_planilla();
        c.show();
        dispose();
    }//GEN-LAST:event_btncodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new planilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncodigo;
    private javax.swing.JButton btnrepositorio;
    private javax.swing.JButton btnvideo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
