/**
 * Bryan estuardo mazariegos Davila
 * Carnet: 09001-17-1001
 */
package excel;


import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.SqlUsuarios;
import modelo.hash;
import modelo.usuarios;

public class login extends javax.swing.JFrame {
    public static login frmLog;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar la forma en la pantalla
         this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/HojaDeCalculo.PNG")).getImage());//Le coloca un icono a al jFrame y también al icono de barra de tareas
        btnIngresar.setIcon(new ImageIcon("Iconos/ingresar4.PNG"));
        btn_regresar.setIcon(new ImageIcon("Iconos/REGRESAR.PNG"));
        jLabel4.setIcon(new ImageIcon("Iconos/admin.PNG"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        Eti_titulo = new javax.swing.JLabel();
        etiqueta_ingresar = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();
        regresar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(0, 153, 153));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 80, 70));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 217, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 217, -1));

        Eti_titulo.setFont(new java.awt.Font("Fredericka the Great", 1, 36)); // NOI18N
        Eti_titulo.setForeground(new java.awt.Color(0, 153, 153));
        Eti_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eti_titulo.setText("Inicio sesión");
        getContentPane().add(Eti_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 459, 50));

        etiqueta_ingresar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        etiqueta_ingresar.setText("Ingresar");
        getContentPane().add(etiqueta_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        btn_regresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 80, 70));

        regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regresar.setText("Salir");
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 80, 70));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
        SqlUsuarios modSql = new SqlUsuarios();
        usuarios mod = new usuarios();
        
        Date date = new Date();
        DateFormat fechaHora = new SimpleDateFormat("yyy-MM-dd HH:mm:ss");
                
        String pass = new String (txtPassword.getPassword());
        
        if(!txtUsuario.getText().equals("") && !pass.equals("")){
            String nuevoPass = hash.sha1(pass);
            
            mod.setUsuario(txtUsuario.getText());
            mod.setPassword(nuevoPass);
            mod.setLast_session(fechaHora.format(date));
            
            if(modSql.login(mod)){
                
                //GestionExcel frMP = new GestionExcel();
                ModeloExcel modeloE = new ModeloExcel();//Se crea una variable de tipo ModeloExcel
                hoja vistaE = new hoja();//se hace una variable de tipo Hoja
                ControladorExcel contraControladorExcel = new ControladorExcel(vistaE, modeloE);//Se hace una variable tipo controlador y en dicha se envia la variable de  Hoja y Modelo Excel
                vistaE.setVisible(true);//se muestra el jframe de hoja.
                 //vistaE.show();//funcion para mostrar la siguiente ventana
                dispose();
                
                JOptionPane.showMessageDialog(null,"Bienvenido: " + txtUsuario.getText());
            }else{
                JOptionPane.showMessageDialog(null,"Datos Incorrectos");
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Existen Campos Vacios");
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
      
    }//GEN-LAST:event_formWindowClosing

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
 int codigo = JOptionPane.showConfirmDialog(null,"¿Seguro que desea SALIR ?","ADVERTENCIA",JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
        if (codigo==JOptionPane.YES_OPTION){
            System.exit(0);
        }else if(codigo==JOptionPane.NO_OPTION){
            login ventana = new login();
            ventana.show();
            dispose();
        }
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eti_titulo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel etiqueta_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel regresar;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
