package laboratorio3.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.scene.text.Text;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jose lopez
 */
public class ingreso_empleado extends javax.swing.JFrame {
    private int id,j;
    /**
     * Creates new form ingreso_empleado
     */
   
    public ingreso_empleado() {
        initComponents();
        this.setTitle("INGRESO DE EMPLEADOS");
        this.setLocationRelativeTo(ingreso_empleado.this);
        this.setResizable(false);
            
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/planilla", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from departamento");
            cbbdepartamento.removeAllItems();
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next())
            {
            cbbdepartamento.addItem(rs.getString(2));
            }
            
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"NO SE PUDO REALIZAR LA ACCION"+e);
        }
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/planilla", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from puesto");
            ResultSet rs = pst.executeQuery();
            cbbpuesto.removeAllItems();
            while(rs.next())
            {
            cbbpuesto.addItem(rs.getString(2));
            }
            
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"NO SE PUDO REALIZAR LA ACCION"+e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        cbbpuesto = new javax.swing.JComboBox<>();
        cbbdepartamento = new javax.swing.JComboBox<>();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        lblpuesto = new javax.swing.JLabel();
        lbldepartamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(516, 469));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("NOMBRE EMPLEADO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel4.setText("SUELDO EMPLEADO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setText("PUESTO EMPLEADO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setText("DEPARTAMENTO EMPLEADO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 190, -1));
        getContentPane().add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, -1));

        cbbpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbpuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbpuestoItemStateChanged(evt);
            }
        });
        cbbpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbpuestoActionPerformed(evt);
            }
        });
        getContentPane().add(cbbpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 190, -1));

        cbbdepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbdepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbdepartamentoItemStateChanged(evt);
            }
        });
        cbbdepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbdepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(cbbdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 190, -1));

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        btnregresar.setText("REGRESAR");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        lblpuesto.setText("jLabel1");
        getContentPane().add(lblpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        lbldepartamento.setText("jLabel2");
        getContentPane().add(lbldepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbpuestoActionPerformed
  
    }//GEN-LAST:event_cbbpuestoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        MENUPRINCIPAL v = new MENUPRINCIPAL();
            v.show();
            dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_btnregresarActionPerformed

    private void cbbdepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbdepartamentoActionPerformed
    }//GEN-LAST:event_cbbdepartamentoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
         codigo();
           try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/planilla", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into empleado values(?,?,?,?,?)");
            String codigo = Integer.toString(id);
             pst.setString(1, codigo);
            pst.setString(2, txtnombre.getText().trim());
            pst.setString(3, txtsueldo.getText().trim());
            pst.setString(4, lblpuesto.getText().trim());
            pst.setString(5, lbldepartamento.getText().trim());
            pst.executeUpdate();
            txtnombre.setText("");
            txtsueldo.setText("");
           JOptionPane.showMessageDialog(null,"INGRESO EXITOSO");
            }catch (Exception e){
             System.out.println("MENSAJE DE PRUEBA"+e);
            }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void cbbpuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbpuestoItemStateChanged
              try{
	Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/planilla", "root", "");
        PreparedStatement pst = cn.prepareStatement("select codigo_puesto from puesto where nombre_puesto = '"+(String)cbbpuesto.getSelectedItem()+"'");
        ResultSet rs = pst.executeQuery();
	if(rs.next())
        {
        lblpuesto.setText(rs.getString(1));
        }
		}
		catch (Exception  abc){
		JOptionPane.showMessageDialog(null,"error" + abc);
		}
    }//GEN-LAST:event_cbbpuestoItemStateChanged

    private void cbbdepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbdepartamentoItemStateChanged
             try{
	Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/planilla", "root", "");
        
        PreparedStatement pst = cn.prepareStatement("select codigo_departamento from departamento where nombre_departamento = '"+(String)cbbdepartamento.getSelectedItem()+"'");
        ResultSet rs = pst.executeQuery();
	if(rs.next())
        {
        lbldepartamento.setText(rs.getString(1));
        }
		}
		catch (Exception  abc){
		JOptionPane.showMessageDialog(null,"error" + abc);
		}
    }//GEN-LAST:event_cbbdepartamentoItemStateChanged
public void codigo()
{
  try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/planilla", "root", "");
            PreparedStatement pst = cn.prepareStatement("select count(*) from empleado");
            ResultSet rs = pst.executeQuery();
            
          String fila = "";
          if(rs.next())
          {
          fila = rs.getString(1);
          j = Integer.parseInt(fila);
          if(j == 0)
          {
          id = 1;
          }else
          {
          id= j+1;
          }
          }
            
        }catch (Exception e){
             JOptionPane.showMessageDialog(null,"ERROR"+e.getMessage());
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingreso_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingreso_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingreso_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingreso_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingreso_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbbdepartamento;
    private javax.swing.JComboBox<String> cbbpuesto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbldepartamento;
    private javax.swing.JLabel lblpuesto;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsueldo;
    // End of variables declaration//GEN-END:variables
}
